require(sqldf)
file <- c("./data/household_power_consumption.txt")
data_subset <- read.csv.sql(file, header = T, sep=";", sql = "select * from file where (Date == '1/2/2007' OR Date == '2/2/2007')" )
data_subset$datetime<-as.POSIXct(paste(data_subset$Date,data_subset$Time), format="%d/%m/%Y %H:%M:%S")
hist(data_subset$Global_active_power, col="red")